# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ryqCH_-h3V8PS8cURXozr4PWniL_R7-k
"""

n = int(input("Digite um número inteiro: "))

while n > -1:
  fatorial = 1
  while n > 1:
      fatorial = fatorial * n
      n = n - 1
  print(fatorial)
  break